settings:
  title: 'Hypercode Services Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hypercode-pl
    name: hypercode.pl
    description: 'Main site'
    url: 'https://hypercode.pl'
    method: GET
    expectStatus: 200
  - id: lo32lodz
    name: lo32lodz.pl
    description: 'XXXII Liceum Ogólnokształcące'
    url: 'https://lo32lodz.pl'
    method: GET
    expectStatus: 200
  - id: zso1lodz
    name: zso1lodz.pl
    description: 'Zespół Szkół Ogólnokształcących nr 1'
    url: 'https://zso1lodz.pl'
    method: GET
    expectStatus: 200
